//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BladderminProtocol {
    
    private string versionField;
    
    private BladderminProtocolProtocolMetaData[] protocolMetaDataField;
    
    private BladderminProtocolConstraints[] constraintsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProtocolMetaData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BladderminProtocolProtocolMetaData[] ProtocolMetaData {
        get {
            return this.protocolMetaDataField;
        }
        set {
            this.protocolMetaDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Constraints", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BladderminProtocolConstraints[] Constraints {
        get {
            return this.constraintsField;
        }
        set {
            this.constraintsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BladderminProtocolProtocolMetaData {
    
    private string nameField;
    
    private string nodesTreatableField;
    
    private string multiPhaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NodesTreatable {
        get {
            return this.nodesTreatableField;
        }
        set {
            this.nodesTreatableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MultiPhase {
        get {
            return this.multiPhaseField;
        }
        set {
            this.multiPhaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BladderminProtocolConstraints {
    
    private BladderminProtocolConstraintsConstraint[] constraintField;
    
    private string nodesField;
    
    private string multiPhaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Constraint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BladderminProtocolConstraintsConstraint[] Constraint {
        get {
            return this.constraintField;
        }
        set {
            this.constraintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nodes {
        get {
            return this.nodesField;
        }
        set {
            this.nodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string multiPhase {
        get {
            return this.multiPhaseField;
        }
        set {
            this.multiPhaseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class BladderminProtocolConstraintsConstraint {
    
    private string nameField;
    
    private string doseValueField;
    
    private string doseUnitField;
    
    private string volumePresentaitionField;
    
    private string volumeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DoseValue {
        get {
            return this.doseValueField;
        }
        set {
            this.doseValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DoseUnit {
        get {
            return this.doseUnitField;
        }
        set {
            this.doseUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VolumePresentaition {
        get {
            return this.volumePresentaitionField;
        }
        set {
            this.volumePresentaitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private BladderminProtocol[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BladderminProtocol")]
    public BladderminProtocol[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
