//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace BladderMinExtentions
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class BladderminProtocol
    {

        private BladderminProtocolProtocol[] protocolsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Protocol", IsNullable = false)]
        public BladderminProtocolProtocol[] Protocols
        {
            get
            {
                return this.protocolsField;
            }
            set
            {
                this.protocolsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BladderminProtocolProtocol
    {

        private BladderminProtocolProtocolPrescription prescriptionField;

        private BladderminProtocolProtocolConstraint[] constraintsField;

        private string protocolDisplayNameField;

        /// <remarks/>
        public BladderminProtocolProtocolPrescription Prescription
        {
            get
            {
                return this.prescriptionField;
            }
            set
            {
                this.prescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Constraint", IsNullable = false)]
        public BladderminProtocolProtocolConstraint[] Constraints
        {
            get
            {
                return this.constraintsField;
            }
            set
            {
                this.constraintsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProtocolDisplayName
        {
            get
            {
                return this.protocolDisplayNameField;
            }
            set
            {
                this.protocolDisplayNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BladderminProtocolProtocolPrescription
    {

        private decimal doseField;

        private bool doseFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Dose
        {
            get
            {
                return this.doseField;
            }
            set
            {
                this.doseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DoseSpecified
        {
            get
            {
                return this.doseFieldSpecified;
            }
            set
            {
                this.doseFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class BladderminProtocolProtocolConstraint
    {

        private string constraintNameField;

        private decimal doseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConstraintName
        {
            get
            {
                return this.constraintNameField;
            }
            set
            {
                this.constraintNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Dose
        {
            get
            {
                return this.doseField;
            }
            set
            {
                this.doseField = value;
            }
        }
    }
}